name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
 

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ci-cd .
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ci-cd .

      - name: Tag image
        run: docker tag ci-cd ${{ secrets.DOCKER_HUB_USERNAME }}artur.baghdasaryan94@gmail.com/ci-cd:latest && docker push ${{ secrets.DOCKER_HUB_USERNAME }}artur.baghdasaryan94@gmail.com/ci-cd:latest 

     
  
  
